# Generated by Django 6.1.1 on 2026-09-04 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcaShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('transfer', 'Transfer'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0, max_length=5)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
