# Generated by Django 6.1.1 on 2026-09-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarcaShop',
            new_name='Product',
        ),
    ]
